# PHP核心编程-day1 #
# 前言: 

  ==学前端为什么要学php?==

- 从个人来讲： 

​       ==了解后端开发流程之后，有利于项目沟通==

​       懂的越多，薪资越高

-    从公司来讲：

​       公司老板也希望你能够承担更多工作，一个人当两个人用

​    PHP是现在非常流行的一种后端开发语言，常见的语言还有：JSP、ASP.NET、 Ruby等。相对于其他的语言来讲，PHP更容易上手，并且开发速度快、功能强大。



每日目标:

- 说出什么是服务器，什么是web服务器

- 说出PHP的作用

- 能够独立安装phpstudy

- 能够说出IP、DNS、端口是什么

- 理解PHP的运行原理

- 掌握PHP基本语法规则

  

# 1. web服务器 #
   问题: 当我们写好一个html文件，放在桌面上时，别人能不能通过浏览器访问？
   答: 不行。 必须将我们的html文件放入==web服务器==，其他人通过网络才能访问。
##   1.1 什么是服务器？ ##
   服务器可以从硬件、软件(系统软件、应用软件)两个角度描述。

   按硬件描述： 服务器就是一台超级计算机。
   按系统划分： 在硬件上安装了什么操作系统，就可以称为该系统的服务器
	                   例如:  linux服务器、windows服务器、unix服务器等。
   按软件划分： 在操作系统中安装了什么软件，就可以称作该软件的服务器
	                   例如:  ==web服务器、数据库服务器==、邮件服务器等。



##   1.2 Web服务器 ##
  Web服务器就是安装了Web服务软件，能够提供网站服务的服务器。淘宝、京东、新浪等等

  常见的Web软件：
    ==Apache==、Nginx、IIS、Tomcat、Node等。
    Apache服务器、Nginx服务器、IIS服务器、Tomcat服务器、Node服务器

​    Apache是世界使用排名第一的Web服务器软件。我们将编写好的html、css、js等文件存入apache，就能够通过网络来访问这些文件了。

​    PS: web服务器又叫做http/httpd服务器



![1527767382808](assets/1527767382808.png)



# 2. PHP概述 #
##    2.1 PHP简介 ##
​        PHP（外文名:PHP: Hypertext Preprocessor，中文名：“超文本预处理器”）是一种通用开源脚本语言。主要适用于==Web领域的开发==，能够完成==动态网页==的制作。



例如：淘宝的搜索功能，不同的关键词能够动态产生不同的网页。

![1533535903794](assets/1533535903794.png)



##    2.2 PHP特点 ##

- PHP是目前最流行的网站开发语言（B/S结构）之一。

- PHP是一种在服务器端执行的嵌入HTML文档的脚本语言。

- PHP 独特的语法混合了 C、Java、Perl 以及 PHP 自创新的语法。

- PHP是一种解释型弱类型语言 （弱类型  解释执行 / 强类型  编译执行）

- 支持几乎所有流行的==数据库==以及操作系统。

- 源码开放、免费（free）  zend

  

##    2.3 B/S结构和C/S结构 ##
  C/S软件体系结构，即Client/Server (客户机/服务器)结构。
     核心特点：==要下载一个客户端==，例如：QQ、微信、LOL、王者荣耀、绝地求生等。   

  C/S结构的软件，服务器主要做==数据转发==工作。以QQ聊天为例：
     任何两个人聊天的内容都会发送到QQ服务器上，然后再由QQ服务器进行转发

​     王小贱和小仙女聊天
        唐小贱发送一句话，这句话会先发送到QQ服务器，再由QQ服务器转发到小仙女的客户端。

![1525243346757](assets/1525243346757.png)



   B/S软件体系结构，即Browser/Server （浏览器/服务器）结构。
       核心特点：==使用浏览器（Chrome、Firefox等）进行操作==，例如：淘宝、京东、新浪等。

   B/S结构软件，服务器承担了所有业务，浏览器只是用来显示最终内容的。

  

![1525243588778](assets/1525243588778.png)



思考问题： B/S的优势和劣势， C/S的优势和劣势。

 B/S的优势: 部署方便，容易维护。用户使用方便（一个浏览器即可）。
 B/S的劣势: 客户端功能简单

 C/S的优势: 功能强大
 C/S的劣势: 必须下载客户端非常麻烦，升级维护麻烦
# 3. 安装环境 （phpstudy） #

   phpstudy是一个集成环境，集成了Apache（IIS和nginx）、PHP、MySQL。 安装该软件后，PHP开发的程序就能运行了。

##   3.1 准备工作 ##
   解压phpstudy包

![1523379032499](assets/1523379032499.png)



   解压后:

![1523379104282](assets/1523379104282.png)

##   3.2 安装 ##

   双击安装文件即开始安装

   特别注意: **==phpstudy的安装路径中不允许出现中文==**，今后安装所有开发相关的软件时也都安装在英文路径下



![1523379251895](assets/1523379251895.png)



​    此处选择“是”

![1523379346800](assets/1523379346800.png)



   设置防火墙允许访问， ==Apache和MySQL==都要允许

![1523379425748](assets/1523379425748.png)

 

 开启Apache和MySQL服务： ==绿色圆圈表示启动， 红色方块表示停止==

![1523379454261](assets/1523379454261.png)



  测试:  开启任意浏览器，输入下列地址

  127.0.0.1  、  127.0.0.1:80

  localhost  、  localhost:80

![1523379608850](assets/1523379608850.png)



看到上图说明已经安装成功



##   3.3 phpstudy目录结构 ##

![1523380423065](assets/1523380423065.png)

phpstudy集成了 Apache、IIS、nginx三种最常见的web服务器软件和多个版本的PHP，并且通过图形化控制面板（phpstudy.exe）可以自由切换



切换服务器和php版本：  默认使用的是  ==Apache + php-5.4.45==

![1523380821032](assets/1523380821032.png)





## 3.4 Apache目录结构

![1523380676384](assets/1523380676384.png)

![1523380739318](assets/1523380739318.png)



配置文件中带 # 的都是注释项，不带的是有效的配置项

![1523381071356](assets/1523381071356.png)

  

主要配置项：

![1523381009030](assets/1523381009030.png)



重点:

  Listen: 如果报80端口被占用可以修改为其他值，例如：8088

![1523381364324](assets/1523381364324.png)



DocumentRoot: 配置html、css、js、php等文件保存的路径。

浏览器中输入localhost或者127.0.0.1，系统就会去DocumentRoot指定的目录去寻找对应的文件。

![1525313932857](assets/1525313932857.png)



DirectoryIndex:  默认访问文件配置

![1525314000860](assets/1525314000860.png)

localhost =>  localhost/index.html

localhost : 首先在www目录下找 index.html；如果没有index.html，找index.php；如果没有Index.php找index.htm；没有则找 l.php。  如果连 l.php都没有，则会将 www 目录下的所有文件和文件夹以列表形式显示出来



## 3.5 PHP目录结构

![1523380928859](assets/1523380928859.png)

  php.ini: php配置文件。  进入到 php-5.4.45目录



![1525314434763](assets/1525314434763.png)

带 ； 是注释，不带的是有效配置项



##  3.6 WWW目录

   我们今后编写的所有网页文件（html、css、js、php）和网页所需要的资源文件（图片、音频、视频） 都需要保存在该目录下。

![1525244224450](assets/1525244224450.png)



从今天开始的19天课程中，当我们通过浏览器访问任意页面时，都需要在浏览器的url地址栏输入类似地址来进行访问，不论是php文件还是html文件。



**==localhost/index.html       localhost/admin/showlist.php==**

localhost会找  d:/phpstudy/www 目录下的文件



# 4. 初识PHP

## 4.1 第一个程序 --- Hello World

  1) 在WWW目录下创建如下目录结构： php1/code/

  2) 在code目录下创建  hello.php 文件

  3) 使用sublime（或其他编辑器）打开hello.php，编写如下代码

  4) 访问测试 

​     在浏览器中输入：localhost/php1/code/hello.php



![1533694176851](assets/1533694176851.png) 





## 4.2 程序解析

  1) ==php文件不能使用中文进行命名， 浏览器地址栏不允许出现中文== ----  在实际开发中摒弃中文

  2) **==从今天开始的19天，在浏览器中查看任何文件（不管是html还是php）都必须使用localhost==**

  3) PHP程序可以和HTML进行混编，可以写在HTML中的任何位置，head、body，任何标签，任何属性均可

  4) php语言的标记
     ==**<?php**  php代码  **?>**   标准标记==
     <?  php代码  ?>           短标记（需要修改php.ini文件打开）

  5) 指令分隔符：
     PHP语句使用 ‘;’  结束     ==必须==

  6) echo相当于js的 document.write 能够在页面上输出内容，包括输出标签、css样式代码等

  7) php文件中可以编写html、css、js代码，但是html文件中不能编写php代码。也就是说==后缀是php的文件才能编写php代码==



# 5. URL解析 #

##    5.1 URL地址说明 ##
   URL: uniform resource locator  统一资源定位器

​       localhost  <==>  http://localhost:80/index.html （全URL）

-  http: 超文本传输协议
-  localhost: 域名。（一般域名：www.taobao.com，www.sina.com.cn） localhost是特殊域名，每一台电脑都有，并且指向当前使用的电脑
-  80: 端口号。 apache的默认端口号为80，所以可以省略不写  (tips:很多web服务器默认端口都是80 Nginx IIS)
-  index.html: 访问的文件的路径 (localhost指向了 d:/phpstudy/WWW)，所以该url地址访问的是  d:/phpstudy/WWW/index.html文件
-  如果没有指定访问的文件，则默认会访问index.html文件；如果没有index.html文件，则会以列表形式显示当前目录下的所有文件夹和文件

  localhost:  D:\phpStudy\WWW

##    5.2 IP ##
   IP: Internet Protocol  互联网协议，是为计算机网络相互连接进行通信而设计的协议。

​    处于网络（互联网、局域网）上的任何一台计算机都有一个独立的ip地址。
    ip地址由4段3位长度的数字组成， 3位数字的取值范围 0-255。如： 102.15.201.10

   特殊ip:
    127.0.0.1 : 回环地址，每一台电脑都有该ip，指向当前使用的电脑
    192.168.**.* *: 该网段是专门用于做==局域网==的ip段。



##  5.3 域名

   域名（Domain Name）： 每个网站都有一个自己的域名。人们可以在浏览器中输入域名来访问对应的网站。

   淘宝: www.taobao.com

   百度: www.baidu.com

   特殊域名：
          localhost: 本地主机。在浏览器中输入localhost就会访问当前操作的这台电脑的web服务器。



##    5.4 DNS ##
   DNS: Domain Name System  域名系统。在DNS服务器中保存了域名和IP的映射关系。主要工作是将域名转换为IP地址，因为我们通过浏览器访问网站时，实际上是去找对应的IP地址。

   域名: 网站的名称，就相当于人名。
   IP: 网站在网络上的实际地址，就相当于人的住址。

   一般访问网站时都是输入域名的(例如： www.tmall.com  www.163.com)，但是在实际访问时域名会被DNS转换为IP地址。

   DNS工作机制图:

![1533537911304](assets/1533537911304.png)



 hosts文件可以手动设置域名和IP的映射关系

 dns缓存可以保存曾经访问过的域名和IP的映射关系



工作步骤:

1)  在浏览器中输入  www.taobao.com，按下回车

2)  浏览器首先在本机中的 hosts文件和dns缓存中查询，www.taobao.com的IP地址。如果有，则获取该IP地址，然后去访问淘宝服务器。 如果没有，则向dns服务器发送解析请求。

3) dns服务器获取到浏览器请求信息之后， 将域名转换为IP地址，再将IP地址返回给浏览器。

4) 浏览器获取到IP地址，然后通过IP地址访问淘宝服务器。 



 windows下查看dns缓存:
    ipconfig  /displaydns
    ipconfig  /displaydns > c:/dnscache.txt   将dns缓存导入到c:/dnscache.txt文件

 windows下清除dns缓存
    ipconfig  /flushdns



IP地址和域名是不是一一对应的？

  有域名没有IP； 有IP没有域名；一个IP对应多个域名。



##    5.5 端口 ##
​   端口是英文port的意译。端口可以理解为区分服务器上服务的标号。

   已被占用的著名端口号：
    80:   Web端口号， Apache、Nginx、IIS
    21:   FTP端口号， FTP软件
    22:   SSH端口号
    25:   sendmail端口号
    ......

  因为Web服务的默认端口号是80，所以在地址栏可以不输入，但是如果将端口号改为其他的（如：8088），那就必须输入端口号，才能正常访问。



![1527767769377](assets/1527767769377.png)





# 6. PHP运行原理 #

## 6.1 HTML运行原理 ##

![1525248413592](assets/1525248413592.png)

1) 在浏览器的URL地址栏中输入 www.baidu.com/index.html 地址，点回车。请求就发送给百度服务器。
2) 百度服务器找到index.html文件，并将文件的内容返回给浏览器
3) 浏览器接收到index.html中的内容，渲染到页面上。

同理: localhost/a.html ,  则会返回 本机web服务器根目录下 a.html文件的内容。浏览器拿到内容后进行渲染。



## 6.2 PHP运行原理 ##
 ==apache不认识php==
 ==浏览器也不认识php==

 ![1525248877964](assets/1525248877964.png)

 1) 在浏览器地址栏中输入 localhost/index.php ,点回车之后。将请求发送给apache服务器。
 2) 服务器找到 index.php文件之后，转发给php解释器
 3) php解释器将index.php文件中的php代码全部转为html，再返回给apache
 4) apache将处理好的html返回给浏览器，浏览器渲染后就可以看到页面







# 7. PHP的数据类型 #

 PHP数据类型一共有8种:

-  基本类型(标量):

​     整型:     整数， 例如: 10, 234, -20, -35 
     浮点型:  小数,  例如: 3.1415, 2.13, 35.123
     布尔值:  true/false
     字符串:  使用单引号/双引号包含的内容, 例如: ‘abc’, “王者荣耀”

-  复合类型:

​     数组
     对象

-  特殊类型:

​     资源 、 null (空)

# 8. 变量 #
变量命名规则：

-  由字母、数字、下划线组成，必须以字母或者下划线起头
-  变量的长度可以是任意的，但不能超过255个字符
-  最前面需要加 $
-  变量名最好有意义，能够做到见名知意
-  当变量名由多单词组成时，最好使用下划线分割或者使用驼峰命名法
-  PHP变量区分大小写



```
<?php 
// 正确的变量名
$int = 123;
$str = 'abc';
$str1 = "def";

// 变量名区分大小写
$INT = 234;

echo $int;
echo $INT;

// 推荐的变量名
$goods_name = "华为 保时捷";
$goodsPrice = 10888;

$a = 'big';
$big = 123;
echo $$a;  //可变变量  echo $big
?>
```



以下变量名哪些是正确的：

```
$a、  $var、  $_123、  $1b、  $_#abc、  $b1c2  
```



# 9.双引号和单引号的区别

  双引号中的变量会被解释为值，单引号中的变量会被解释为字符串

  单引号的执行速度会快于双引号的速度




# 10. 常量 #
 保存不会发生改变的数据(如：3.1415， 路径等)时，最好使用常量。

 常量的使用方法：
   1) 声明:  define(常量名,  常量值,  大小写区分标志);   

​	true（不区分）/false（区分/默认）;

   2) 调用:  echo  常量名;

![1533698709352](assets/1533698709352.png)







# 11. 运算符 #
##    11.1 运算符种类 ##
- 算术运算符

- 字符串运算符
- 赋值运算符
- 比较运算符
- 逻辑运算符
- 其他运算符



 算术运算符：

![img](assets/wpsEA60.tmp.jpg)



特殊案例:

```
$str = "abc";
$int = 20;
echo $str + $int;   //20

$str = "5";
$int = 20;
echo $str + $int;   //25
```





 赋值运算符：

![img](assets/wps7D4D.tmp.jpg)

`$a += $b   $a = $a + $b`



 比较运算符：

![img](assets/wpsCF.tmp.jpg)



 逻辑运算符：

![img](assets/wps5CD4.tmp.jpg)


  异或: (了解)
     true   xor   true   =  false
     true   xor   false  =  true
     false  xor   true   =  true
     false  xor   false  =  false



  其他运算符：

![img](assets/wps3355.tmp.jpg)

   三元运算符:   判断表达式？值1：值2

​    

   php默认内置有4种错误： 
        notice： 通知错误
        Warning error： 警告错误
        Parse error： 解析错误
        Fatal error： 致命错误 



@不能屏蔽掉所有的错误。 也不建议在实际开发中使用该符号。

```
<?php 
// 语法错误是不能被屏蔽掉的
@$books = "JavaScript"
echo $books;

// 大多数其他错误是可以被屏蔽掉的
@abc();
?>
```





##   11.2 字符串链接运算符 ##
   字符串拼接:   .  

  



# 12. 流程控制 #
##   12.1 选择结构  (if...else) ##
```
if(判断表达式){
	程序块1;
} else {
	程序块2;
}

if(判断表达式){
	程序块;
} elseif(判断表达式) {
	程序块;
} ...{
} else {
	程序块;
}
```

 

案例1: 判断三个变量中的最大值

```
header('content-type:text/html;charset=utf-8');
$a = 40;
$b = 50;
$c = 30;

if ($a > $b) {
    if ($a > $c) {
        echo '最大值是：$a';
    } else {
        echo '最大值是：$c';
    }
} else {
    if ($b > $c) {
        echo '最大值是：$b';
    } else {
        echo '最大值是：$c';
    }
}
```



案例2: 判断时间，提示不同的问候语

```
header('content-type:text/html;charset=utf-8');
$time = 10; //此处应该动态获取当前时间（小时）。因为没有学过动态获取时间，先固定成某个值

if ($time >= 0 && $time < 6) {
    echo "凌晨好";
} else if ($time >= 6 && $time < 12) {
    echo "上午好";
} else if ($time >= 12 && $time < 18) {
    echo "下午好";
} else if ($time >= 18 && $time < 24) {
    echo "晚上好";
} else {
    echo "时间有误";
}

#警示 6 <=  $time  < 12
```





##   12.2 循环结构  (while / for / do...while) ##
```
while(判断表达式){
	程序块;
}

for(赋值表达式; 判断表达式; 步进表达式){
	程序块;
}

do{
	程序块
} while(判断表达式)

下面循环执行几次?
for(i = 1; i == 1; $i++){}
for(i = 1; i = 1; $i++){}
```



案例1: 输出1-100之间的偶数

```
for ($i = 1; $i <= 100; $i++) {
    if ($i % 2 == 0) {
        echo $i . "<br>";
    }
}
```



案例2: 输出九九乘法口诀表

```
for ($i = 1; $i <= 9; $i++) {
    for ($j = 1; $j <= $i; $j++) {
        echo $i * $j . "&nbsp;";
    }
    echo "<br>";
}
```



##   12.3 分支结构  (switch) ##

```
switch(变量){
	case 值1:
		程序块1；
		break;
	case 值2:
		程序块2；
		break;
	...
	default:
		程序块
}
   
变量一般使用 : 整型  字符  字符串
```



案例:  不同语言的"我爱你"

```
header('content-type:text/html;charset=utf-8');
$lang = 'dasdsad';

switch ($lang) {
    case 'zh-cn':
    	echo "我爱你";
    	break;
    case 'en-us':
    	echo "I love you";
    	break;
    case 'de-de':
    	echo "Ich liebe dich";
    	break;
    case 'ja-jp':
    	echo "あなたのことが好きです";
    	break;
    case 'fr-fr':
    	echo "Je t'aime!";
    	break;
    default:
    	echo "语种错误";
    	break;
}
```



##   12.4 特殊语句  (continue、 break) ##
​	contiune: 结束当前循环，直接跳入下一次循环
	break: 结束整个循环

# **PHP核心编程-day2**  

每日目标:

- 能够声明数组、遍历数组
- 能够声明二维数组、遍历二维数组
- 能够说出什么是php超全局变量
- 能够使用get、post两种方式提交表单数据
- 能够说出get和post的区别
- 能够完成文件上传



# 1.数组

## 1.1 数组声明

  var  arr = [123, 'abc', 234];   console.log(arr[1]); 

   PHP的数组分为索引数组和关联数组两类:
     索引数组: ==下标是数字==的数组就是索引数组
     关联数组: ==下标是字符串==的数组就是关联数组 (重点)

   格式:
     $arr = array();
     $arr = [];

```
//声明索引数组
//               0         1         2
$arr1 = array('福禄娃', '海绵宝宝', '猪猪侠');
$arr2 = array(3=>'蜘蛛侠', 6=>'钢铁侠', 10=>'煎饼侠');
$arr3 = ['张无忌', '赵敏', '灭绝师太'];


//声明关联数组 -- 下标是字符串
$info = ['name'=>'张二狗', 'age'=>20, 'gender'=>'男'];
$goods_info = ['goods_name'=>'小米 8', 'goods_price'=>1999];
```



## 1.2 数组读写

   不管是索引还是关联数组，都是通过下标来进行读写控制的。

```
echo $arr2[6];
//下标是字符串，一定要加引号
// 如果不加引号就会变为常量
echo $info['name'];

$goods_info['goods_name'] = '小米 note 3';
```

​     

## 1.3 数组遍历

​    foreach 语句结构，用来遍历数组(关联数组和索引数组均可)。

​    格式: 

```
foreach($arr as $key=>$value){程序体}

foreach($arr as $value){程序体}
```

​      $arr : 要遍历的数组      
      $key: 单元的下标，可以是任意变量名
      $value: 单元的值，可以是任意变量名

```
<?php 
$arr = ['张无忌', '赵敏', '灭绝师太'];

//第一次循环，将第一个单元取出
//将单元的下标，赋值给$key
//将单元的值， 赋值给$value
//第二次循环，将第二个单元取出，赋值步骤同上
foreach ($arr as $key=>$value) {
    echo $key . "-" . $value . '<br>';
}


$goods_info = ['goods_name'=>'小米 8', 'goods_price'=>1999];
foreach ($goods_info as $k=>$v) {
    echo $k . '-' . $v . '<br>';
}

//如果as后面只有一个变量，该变量就是数组的单元值
foreach ($goods_info as $value) {
    echo $value;
}
?>
```



## 1.4 二维数组和多维数组

- 一维数组的单元中，保存了一个数组，那么该数组就是二维数组
- 二维数组可以想象成一个表格
- 二维数组同样也用下标来进行控制
- 二维数组常用来存储一组相似/相关的数据
- 二维数组的每个单元都保存一个一维数组，就是三维数组；三维数组的每个单元都保存一个数组就是四维数组； 依次类推，可以到n维。在一般开发中，最常用的是一维和二维数组，三维极少使用。



![1533544335589](assets/1533544335589.png)



```
//同质数据
$list = [
  0=>['name'=>'zs', 'age'=>20, 'gender'=>'男'],
  1=>['name'=>'ls', 'age'=>21, 'gender'=>'女'],
  2=>['name'=>'ww', 'age'=>19, 'gender'=>'女'],
];
```





## 1.5 遍历二维数组

​     核心思想： 使用foreach取出第一维的数据（数组），第二层通过下标输出



```
$list = [
  0=>['id'=>1, 'name'=>'zs', 'age'=>20, 'gender'=>'男'],
  1=>['id'=>2, 'name'=>'ls', 'age'=>21, 'gender'=>'女'],
  2=>['id'=>3, 'name'=>'ww', 'age'=>19, 'gender'=>'女'],
];

//通常在实际开发当中，都只用一层foreach;
//第二层数据的显示，使用$value[下标]
//$value是一位数组
//第一次循环: $value = ['id'=>1, 'name'=>'zs', 'age'=>20, 'gender'=>'男'];
//第二次循环: $value = ['id'=>2, 'name'=>'ls', 'age'=>21, 'gender'=>'女'];
//第三次循环: $value = ['id'=>3, 'name'=>'ww', 'age'=>19, 'gender'=>'女']
foreach ($list as $key=>$value) {
    echo $value['id'] . ' ';
    echo $value['name']. ' ';
    echo $value['age']. ' ';
    echo $value['gender'];
    echo "<br>";
}
```



## 1.6 将数组输出成一个表格

方式一 : 使用echo来输出整体的表格结构，再用foreach来循环输出tbody中的结构和数据

```
$list = [
  0=>['id'=>1, 'name'=>'zs', 'age'=>20, 'gender'=>'男'],
  1=>['id'=>2, 'name'=>'ls', 'age'=>21, 'gender'=>'女'],
  2=>['id'=>3, 'name'=>'ww', 'age'=>19, 'gender'=>'女'],
];

echo "<table border='1' width='600'>";
echo "<thead>";
echo "<tr>";
echo "<th>编号</th><th>姓名</th><th>年龄</th><th>性别</th>";
echo "</tr>";
echo "</thead>";
echo "<tbody>";
//以第一次循环为例
//$value = ['id'=>1, 'name'=>'zs', 'age'=>20, 'gender'=>'男'];
foreach ($list as $value) {
    echo "<tr>";
    echo "<td>".$value['id']."</td>";
    echo "<td>".$value['name']."</td>";
    echo "<td>".$value['age']."</td>";
    echo "<td>".$value['gender']."</td>";
    echo "</tr>";
}
echo "</tbody>";
echo "</table>";
```



方式二: 提前定义好表格结果，只循环tbody中的内容

```
<?php 
//同质数据
$list = [
  0=>['id'=>1, 'name'=>'zs', 'age'=>20, 'gender'=>'男'],
  1=>['id'=>2, 'name'=>'ls', 'age'=>21, 'gender'=>'女'],
  2=>['id'=>3, 'name'=>'ww', 'age'=>19, 'gender'=>'女'],
];
?>
<table border="1" width="600" class="a">
    <thead class="b" style="color:red">
        <tr>
            <th>编号</th>
            <th>姓名</th>
            <th>年龄</th>
            <th>性别</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($list as $value) { ?>
        <tr>
            <td><?php echo $value['id']; ?></td>
            <td><?php echo $value['name']; ?></td>
            <td><?php echo $value['age']; ?></td>
            <td><?php echo $value['gender']; ?></td>
        </tr>
        <?php } ?>
    </tbody>
</table>
```





## 1.7 print_r函数

   该函数不但能够输出基本类型，还能够输出数组，在项目开发时经常使用该函数查看数组中的所有数据。

   debug的核心思想就是跟踪变量，一段程序中所有变量中保存的是自己需要的数据，程序才在自己的掌控之下。

```
$info = ['id'=>10001, 'name'=>'张飞', 'age'=>21, 'gender'=>'男'];
print_r($info);
```

![1533781004203](assets/1533781004203.png)

```
$list = [
  0=>['id'=>1, 'name'=>'zs', 'age'=>20, 'gender'=>'男'],
  1=>['id'=>2, 'name'=>'ls', 'age'=>21, 'gender'=>'女'],
  2=>['id'=>3, 'name'=>'ww', 'age'=>19, 'gender'=>'女'],
];
print_r($list);
```

![1533781034981](assets/1533781034981.png)



使用 echo  来输出数组，则会得到以下错误

![1533781096919](assets/1533781096919.png)



## 1.8 课后作业

![img](assets/wps8E34.tmp.jpg)





数组应该是一个 二维数组， 需要保存3个数据，图片地址、人物名称、图片尺寸。

图片展示是 ul 和 li 组成。每一组li应该显示一组信息。



# 2. 超全局变量(预定义数组)

## 2.1 什么是超全局变量

​    超全局变量是PHP内置的变量，在每一个php文件中都可以直接使用。

​    特点: 
	在每个页面都能直接使用
	内部都是==关联数组==结构

```
非常重要: $_GET、$_POST、$_SESSION、$_COOKIE、$_FILES
知道: $_SERVER、$_REQUEST、$GLOBALS
```

 

## 2.2 $_SERVER

$_SERVER记录了服务器和客户端的主要信息，和当前页面的信息

 ![1533782283446](assets/1533782283446.png)



重点记住的内容:

  REQURES_URI ： 访问的文件地址

  SCRIPT_NAME： 脚本名称（路径）

  PHP_SELF： 自身文件名

  访问的文件的绝对路径。 此处的绝对路径是和域名绝对

   /php2/code/server.php -->  localhost/php2/code/server.php





## 2.3 get/post方式接收表单数据

  表单处理通常需要两个页面：

​      1)  form.html，表单页，用户可以在表单页上填写相关数据

​      2)  form.php ,  数据接收处理页， 接收用户在表单填写的数据，然后做进一步处理

![1525418662232](../%E7%AC%94%E8%AE%B0/assets/1525418662232.png)





代码实现：

form.html

![1533783297322](assets/1533783297322.png)



form.php

![1533783312171](assets/1533783312171.png)



注意:  表单中每个域的name值，会作为$_POST的下标







  表单提交关键点总结:

  表单页: form.html

​    1) 必须有form表单标签，form必须有action 和 method 两个属性

- action: 指定表单数据提交的位置 ---  php/jsp/asp文件的路径
- method: 表单提交的方式， post 、get(默认)

​    2) 每个表单域都要有name属性    input   select   textarea

​    3) 必须有submit类型的按钮

   

   数据接收处理页： form.php

​    1) method=post时，使用$_POST接收数据    

​    2) method=get时，使用$_GET接收数据

​    3) 不管是`$_POST`还是`$_GET`，都是一个关联数组，数组的下标就是表单域中 name 属性的值





## 2.4 每种域和类型的提交方式

  表单标签： form 、 ==input 、 select 、 textarea==

  ==表单提交的实际上是每个域的value值==

  1) input  type= text/password/hidden/email  提交的就是value属性中的值

  2) input  type=radio  提交的是选中项的value值。==value必须设置，否则后端会接收 on==

  3) input  type=checkbox  ==在name的值后增加[] 转换成数组结构==，后端才能接收到所有的已勾选项

  4) select  name值需要定义在select标签中； value定义在option中，每条option都有自己的value

​                 如果不定义option中的value，则会将option中间的内容发送到后端页面中

  5) textarea  name值定义在textarea标签中，value没有显式的表示出来，就是开始标签和结束标签之间的内容



![1533784655977](assets/1533784655977.png)





## 2.5 post和get的区别 (非常重要)

==通过URL地址栏来区分post和get==

get将提交数据拼接成字符串显示在URL地址栏中

![1525423939656](../%E7%AC%94%E8%AE%B0/assets/1525423939656.png)

post不显示

![1525423862000](../%E7%AC%94%E8%AE%B0/assets/1525423862000.png)

 

1) 提交方式

- get会将数据显式的拼接到url地址栏中  (字符串)

  例如： form.php==?==id=10001==&==username=heiheihei==&==passwd=123456&key=value....
  key=value方式传参，多个参数之间使用&符号隔开

​         id、username、passwd等等（键/key）都是表单域的name值

​         1、heiheihei、123456等等（值/value）都是表单域的value值

- post不会显示出来

2) 传递数据量大小

- post最小值是2M，默认8M，可以通过修改php配置(php.ini)文件来修改大小，理论上没有上限的。

- get会受到浏览器的地址栏的限制。有的是2k，有的是8K(chrome)

3) 应用范围不一样

- post在绝大多数情况下都使用在表单提交中。

- get的应用范围比较广。在a标签的href中，location.href中等都能使用get方式。



![1533786580917](assets/1533786580917.png)

 

## 2.6 $_REQUEST

   $_REQUEST 即可以接收get方式提交的表单，也能接收post方式提交的表单。但是因为速度比较慢，所以现在被弃用。







# 3. **文件上传**

  文件上传属于一种特殊的表单提交，也需要两个页面 ---  表单页  和   数据处理页。

![1525424869723](../%E7%AC%94%E8%AE%B0/assets/1525424869723.png)



upload.html表单页

![1533787848965](assets/1533787848965.png)



upload.php 上传文件处理页

![1533788030706](assets/1533788030706.png)





文件上传核心点总结:

 核心点一：表单设计 

​	表单标签form中必须额外增加 enctype属性，必须使用post提交表单

​	文件域必须有name属性和值



 ==核心点二  ---  $_FILES==

$_FILES是一个二维数组，保存了上传文件的相关信息：

 第一维下标是 文件域的name值

 第二维有5个固定单元

   name: 上传的文件名

   type: 上传的文件类型

   tmp_name: 上传文件在服务器临时存储的路径

   error:  错误码，错误码有0-4  5个值。 等于0时，代表文件正常上传

​      0：代表正常上传，没有错误

​      1：代表上传文件大小超过了 php.ini中 upload_max_filesize 定义的大小

​      2：代表上传文件大小超过了 php.ini中 post_max_size 定义的表单最大值

​      3：文件只有部分被上传 

​      4：没有文件被上传 

   size: 上传文件的大小  bit



![1533545384816](assets/1533545384816.png)







 ==核心点三  ---  move_uploaded_file==

从$_FILES中我们可以知道，文件已经正常上传到服务器了。

所以，接下来就需要将文件从临时保存路径，移动到我们希望保存的路径中。

move_uploaded_file (参数1， 参数2)；

 参数1: 临时路径  --->  `$_FILES['pic']['tmp_name']`

 参数2: 目标路径  --->  使用相对路径移动到当前目录下   ./ 





作业2： 只允许上传图片 （jpg  png  gif）

字符串截取:  strpos   substr

数组函数:  in_array

# PHP核心编程-day3

每日目标

- 掌握PHP函数声明和调用方法
- 掌握PHP中变量作用域规则
- 掌握文件引入的四个函数
- 掌握PHP的常用函数
- 能够完成壁纸列表和添加壁纸操作



# 1. 函数

## 1.1 什么是函数？

   函数（function）是一段完成指定任务的已命名代码块

   PHP函数包括内置函数（系统函数）和自定义函数两类



## 1.2 函数的格式

   PHP声明函数的方式和Javascript一致。 

```
function  函数名称（[参数1 [,参数2 [,…]]]）
{
	函数体;
	
	//如需函数有返回值时使用
	[return 返回值;]
} 
```



## 1.3 变量的作用域

  核心概念: 在函数体外定义的变量，在函数体内无效
 	  	   在函数体内定义的变量，在函数体外无效



![1533949815695](assets/1533949815695.png)



  全局变量 和 局部变量:
	局部变量:  函数体内的变量，该变量只在函数范围内有效。
	全局变量:  函数体外的变量，在整个php文件中都有效（除了函数）。





## 1.4 文件包含

  文件包含一共有4个函数:   include、include_once、require、require_once
  ==文件A中包含文件B，那么文件B就相当于文件A的一部分。==

  注意事项: 
    如果文件A和文件B定义了相同的变量，则会发生覆盖。
    如果文件A和文件B定义了相同的函数，则会发生致命错误。



​    include             require

​    include_once   require_once



四个语句的区别：

1) include在包含一个不存在的文件时，会产生一个Warning错误，程序不会中断继续执行；而require会产生Fatal错误，中断执行。

2) include_once和require_once的区别：include_once只会加载一次相同的文件，而inlcude会加载多次。

3) 在实际开发中基本使用 include_once或者require_once





## 1.5 static静态变量

   当一个变量使用static进行修饰时，该变量在整个php页面运行过程中只有一份。

  ![1533888584603](assets/1533888584603.png)



​    每次调用 aaa() 函数时，都会去静态内存区寻找是否有 `$i`。如果没有，则创建`$i`并进行赋值；如果有，则直接使用，跳过赋值过程。

​    static在递归操作中非常有用。



## 1.6 global全局变量

​    如果在一个函数体内想强行使用函数体外定义的变量，可以使用global关键词来声明。

![1533952559547](assets/1533952559547.png)

  

​      $GLOBALS的功能和global差不多，都不推荐使用。



# 2. 常用函数

##  2.1 日期函数

```
int time():  获取当前时间点的时间戳 -- 1970.1.1 00:00:00 到现在的秒数
string date(format $str, timestamp $int): 可以将时间戳转为年月日时分秒的形式
```

2018-08-11 10:10:10



```
date函数说明：

参数1: 要显示的时间格式
参数2: 时间戳, 可选参数, 如果不指定则为当前时间戳
返回值: 指定的时间格式

时间格式参数:
Y: 4位年
m: 带前导0的2位月
d: 带前导0的2位日
H: 带前导0的2位时
i: 带前导0的2位分
s: 带前导0的2位秒

修改时区有两种方法:
1)  使用函数 ---- date_default_timezone_set();      临时修改
2)  修改php配置文件 php.ini                         永久修改
北京时间: PRC (中国人民共和国)  或者  asia/shanghai (亚洲/上海)
```



在php.ini文件中永久修改时区的配置项

![1533953422928](assets/1533953422928.png)



重启apache服务器，才能使最新的配置项生效。 （只要修改过Apache或者php的配置文件，就都需要重启Apache服务器才能生效。Apache配置文件 httpd.conf）



![1533953606233](assets/1533953606233.png)



##  2.2 变量函数

```
bool empty($var): 判断变量是否为空。如果为空返回 true；反之，则返回false
bool isset($var): 判断一个变量是否被设置。 如果已设置返回true，反之，返回false
void unset($var): 删除变量，无返回值
```





##  2.3 数组函数

```
bool in_array(mixed, arr):  检查一个值是否存在于一个数组当中
array explode(delimiter, str): 使用一个字符串将另一个字符串分割为数组
string implode(str, arr):  使用一个字符串将一个数组链接为字符串
```





## 2.4 字符串函数

```
int strlen(str):  获取字符串长度
int strpos/strrpos($str, $char): 查询$char字符串在$str字符串中的第一次/最后一次出现的下标
string substr（str, start[, length]）:  字符串截取
string str_replace（search, replace, str）:  字符串替换
string trim（str）:  删除字符串左右两边的空格
void die/exit([str]): 结束当前脚本
```





# 3. 文件读写

## 3.1 读取文件内容

```
string  file_get_contents(string $file);
参数: 文件路径，可以是本地文件的路径，也可以是网络地址
返回值: 文件内容
```

```
/**
 * 获取文件内容
 * 参数: 要获取的文件的路径，该路径可以是本地文件路径，
 *       也可以是网络文件路径
 * 返回值: 文件内容
 */
echo file_get_contents('./data.txt');

echo file_get_contents('http://s1.bdstatic.com/r/www/cache/static/home/css/index.css');
```





## 3.2 向文件中写入内容

```
int file_put_contents(string $file, string $data[, constants flag]);
参数1: 文件路径
参数2: 要写入文件的字符串
参数3: 可选参数，默认不写，新内容覆盖原文件中的内容；FILE_APPEND是向文件中追加内容
返回值: 写入文件的字符串长度
```









## 3.3  序列化 和 反序列化

   file_put_contents函数不能将数组直接写入文件，因为数组不能直接转化为字符串。

   string  ==serialize==($arr):   将数组转为字符串，该字符串是一种特殊结构的字符串。
   array  unserialize(string):   将序列化的字符串转为数组



序列化:

```
$arr = [
    ['name'=>'张飞', 'size'=>'1920*1200', 'path'=>'./pic/11.jpg'],
    ['name'=>'吕布', 'size'=>'1920*1200', 'path'=>'./pic/10.jpg'],
    ['name'=>'安琪拉', 'size'=>'1920*1200', 'path'=>'./pic/6.jpg'],
];

/**
 * 能将数组转为带有数组结构的字符串
 */
echo serialize($arr);
```



结果:

```
a:3:{
  i:0;a:3:{
   s:4:"name";s:6:"张飞";
   s:4:"size";s:9:"1920*1200";
   s:4:"path";s:12:"./pic/11.jpg";
  }
  i:1;a:3:{
   s:4:"name";s:6:"吕布";
   s:4:"size";s:9:"1920*1200";
   s:4:"path";s:12:"./pic/10.jpg";
  }
  i:2;a:3:{
   s:4:"name";s:9:"安琪拉";
   s:4:"size";s:9:"1920*1200";
   s:4:"path";s:11:"./pic/6.jpg";
  }
}
```



反序列化:

```
$str = file_get_contents('./data.txt');

/**
 * 将结构化好的字符串转回成数组
 * 参数: 结构化好的字符串
 * 返回值: 数组
 */
$arr = unserialize($str);
print_r($arr);
```



结果:

![1533959168968](assets/1533959168968.png)



# 4.  综合案例--壁纸管理

## 4.1 壁纸列表

目标：以表格形式将data.txt文件中所有的数据展示出来

![1533895818621](assets/1533895818621.png)



思路分析：  

  1) 从文件中读取数据 --- 字符串

  2) 将字符串恢复成数组结构(unserialize) --- 二维数组  

  3) 循环将数据进行输出



代码实现:

![1533960011212](assets/1533960011212.png)

![1533960023460](assets/1533960023460.png)



## 4.2 添加新壁纸

![1533892050303](assets/1533892050303.png)



 思路分析:  三个文件完成该功能    表单页 、 数据处理页 、 数据保存文件

​    1) 表单页（upload.html）

​         保证数据能够正常提交，文件能够正常上传

​    2) 数据处理页 (upload.php)

​	① 文件上传
	② 接收表单数据
	③ 将数据写入data.txt文件

​             i.  将接收到的数据构造成一个一维数组 ($info)

​             ii. 将data.txt文件中原有的数据取出，反序列化成二维数组 （$list）

​             iii. 将`$info` 追加到 `$list`中

​	     iv. 将$list序列化后，再写回data.txt文件（覆盖）

​    3) 数据保存页 (data.txt)

​        在该文件中保存的数据必须是被序列化过的数组

 

  代码实现:

   add.html

![1533961868828](assets/1533961868828.png)



 add_deal.php

![1533961912216](assets/1533961912216.png)

![1533961954758](assets/1533961954758.png)



![1533961997564](assets/1533961997564.png)





  关键点总结：

  1) 表单页（upload.html）

​     表单要上传文件，所以必须有  enctype属性，必须使用post进行数据提交

  2) 数据处理页（upload.php）

​     ① 因为上传的必须是图片，所以要做检测上传文件类型，还要重命名文件防止覆盖
     ② 创建数组用来保存表单接收的数据，数组应该有三个单元 (name  size  url)
     ③ 要先将data.txt文件中的数据读出来。如果文件为空，则创建一个空数组，再将表单提交的数据追加到数组中；如果文件不为空，则反序列化成一个数组，再将表单数据追加到数组中。
     ④ 将追加后的新数组序列化，再写入data.txt文件中


# PHP核心编程-day4

每日目标

- 能够说出什么是Http协议
- 能够说出什么是请求什么是响应
- 能够列举常见的状态码
- 能够安装Navicat客户端
- 能够掌握MySQL数据库的基本结构





# 1. Http协议

##  1.1 Http协议概述

  协议: 就是事先的一种约定、规则、规范、标准。（租房合同、工作合同）。

  HTTP协议：HyperText Transfer Protocol 超文本传输协议，客户端（浏览器端）与WEB服务器端之间的交互协议。当浏览器和服务器进行数据交换时，html文件、图片、CSS、JS等都是基于HTTP协议进行传输的。

  HTTP协议有两个版本: 1.0 和 1.1，目前使用的基本都是1.1

  特点: 
	通常是基于 B/S 结构软件的。
	无连接: 浏览器向服务器发送一次请求，服务器响应一次，链接即结束。
	无状态: 无记忆。 服务器不能记住哪个浏览器访问过。 

  

无连接 -- 没有持久化链接

当浏览器地址栏输入 www.baidu.com/index.html，按下回车时。浏览器向服务器发送请求，服务器找到index.html文件返回给浏览器之后，本次链接断开。

如果在点击该页面中任何一个链接，则重新建立一次链接。客户端发送请求，服务器响应。之后又断开链接。 

![1528123196860](assets/1528123196860.png)



##  1.2 请求和响应

HTTP协议主要分为两大部分: 
	请求:  访问服务器的任何一个文件都是一次请求
	响应:  服务器处理请求，将结果返回给浏览器。

1) 请求(==request== / http request)
	客户端(浏览器)向服务器索要数据时遵循的协议

 	请求分为3个部分:  请求行   请求头   请求主体

​	请求行:  请求方式、请求URL地址、协议版本号
	请求头:  主机域名，客户端(浏览器)的信息等
	请求主体:  发送给服务器的数据，get和post都会通过请求主体将数据发送给服务器

 	可以使用Chrome tools 或者 firebug 来查看请求和响应的信息（F12）

​       

​        主要请求项:

​	  host： 主机名和端口号，80端口默认不显示
	  accept：可接受的程序类型
	  accept-encoding： 可接受的压缩类型
	  accept-language： 可接受的语言类型
    	  cache-control： 缓存控制



案例1:  访问 localhost/php4/code/http/index.html 文件

![1534037686331](assets/1534037686331.png)



通过F12进行查看

![1534037719460](assets/1534037719460.png)

点击 index.html就能看到右侧的三个信息

![1534037758865](assets/1534037758865.png)



![1534037865601](assets/1534037865601.png)





案例2:  index.html表单数据提交到index.php文件

![1534038374457](assets/1534038374457.png)

![1534038385472](assets/1534038385472.png)



post方式提交的数据叫  FormData，以字符串形式将数据进传递

![1534038450547](assets/1534038450547.png)



案例3:  index.html页面中a标签跳转到get.php文件

![1534038586471](assets/1534038586471.png)



![1534038596860](assets/1534038596860.png)



![1534038629048](assets/1534038629048.png)



get传值叫做  Query String Parameters

![1534038670110](assets/1534038670110.png)



 

2) 响应(==response== / http response)

​	响应也分为3部分:  响应行   响应头   响应主体

​	响应行: 协议版本号、响应结果==状态码==
	响应头: 主要是服务器端的信息
	响应主体: 就是从服务器返回给客户端的数据

​        主要响应项：

​	  content-type： 响应内容类型， content-type:text/html，服务器告诉浏览器，返回的这部分数据是文本类型，使用html方式来解析即可。
	  content-length： 响应内容的长度 ，content-length:336, 从服务器返回给浏览器的数据总长度为336字节



案例1: 访问 localhost/php4/code/http/index.html 文件时的响应信息

![1534038956636](assets/1534038956636.png)



![1534039173890](assets/1534039173890.png)





案例2: index.html表单数据提交到index.php文件的响应信息



案例3: index.html页面中a标签跳转到get.php文件的响应信息

 



##  1.3 状态码

 常见的状态码如下: 

 200 ok   -----   请求成功

 302 redirect|Found  ----- 重定向

 304 not modified ----- 缓存文件

 403 forbidden   -----  禁止访问 （没有权限访问）

 404 Not Found  -----  未找到页面

 500 internal server error  ----- 服务器内部错误 (可能是服务器本身有问题，或者代码错的太离谱)

 

##  1.4 header响应头设置

1) 设置响应类型

​    浏览器发起请求的方式是多样的，当发起请求后服务端会有对应的内容响应过来，浏览器会根据响应头==Content-Type==来对响应的内容进行解析

​    content-type主要的响应类型是  text/html   
    其他常见类型 :  text/css   text/javascript   image/png  image/jpeg  image/gif

​     注意: 所有的响应类型都是  大范围/小类型， 千万不能写反



案例1: php绘制的验证码 verify.php

![1534040061590](assets/1534040061590.png)

![1534040079302](assets/1534040079302.png)



如果改为 text/html

![1534040111085](assets/1534040111085.png)

![1534040123921](assets/1534040123921.png)



案例2: link标签发送请求 

① 创建html文件，使用link标签引入一个php文件

![1534040360466](assets/1534040360466.png)



② 在h1.php文件中，设置响应类型（content-type为css）

![1534040405398](assets/1534040405398.png)



访问结果:

![1534040433662](assets/1534040433662.png)





2) 指定字符集

   中文字符集: utf-8  gb2312  gbk

​     header(‘Content-Type:text/html;charset=utf-8’);
     header(‘Content-Type:text/html;charset=gb2312’);

 

   页面乱码问题处理方式：
     页面乱码是因为==文件编码==和==页面指定编码==不一致，所以解决该问题就是要==统一文件编码和页面指定编码==

​     ① 在页面中设置 header ，编码指定为 utf-8
     ② 将文件的编码格式，指定为utf-8 (使用sublime，将保存格式设置为 utf-8 或者 使用editplus另存为文件时，设置utf-8)



如果 header设置为 utf-8，则文件编码格式也要设置为 utf-8

如果 header设置为 gbk，则文件编码格式要设置为 ANSI 



① 在sublime创建charset_utf8.php

![1534041680058](assets/1534041680058.png)

访问结果:

![1534041704258](assets/1534041704258.png)



② 在windows中直接创建 charset_gbk.php

![1534041740929](assets/1534041740929.png)



访问结果:

![1534041755891](assets/1534041755891.png)





原因:

  sublime创建的文件是utf-8编码的，和页面中header设置的字符集一致，所以能正常显示。

  windows创建的文件是ANSI编码的, 而页面中header设置的字符集是utf-8，两者不一致，所以乱码了。



解决方案:

  ① windows创建的文件，header要设置为 gb2312或者gbk

  ② 将windows创建的文件，改为utf-8编码



修改文件编码可以使用editplus或者sublime都行

![1534042040846](assets/1534042040846.png)



![1534042064418](assets/1534042064418.png)



现在我们常用的sublime和vs，创建的都是utf-8编码格式的文件，所以，header要设置为 utf-8



3) 页面重定向

​     header('location:页面地址');
     header('refresh:2;url=页面地址');

![1534042530403](assets/1534042530403.png)





扩展内容:

![1534042923833](assets/1534042923833.png)





# 2. MySQL数据库服务器

##  2.1 什么是数据库

存储数据的仓库。

常见的数据库: MySQL、 Oracle、 Sqlserver、 DB2等。

##  2.2 MySQL简介

MySQL是一个关系型数据库管理系统，由瑞典MySQL AB 公司开发，目前属于 Oracle 旗下产品 

MySQL结构：

![img](assets/wps459D.tmp.jpg) 

在一个MySQL服务器中有多个数据库，每个数据库又有多个数据表。 数据是存储在数据表当中的。

数据表的结构和excel一模一样

![img](assets/wps459E.tmp.jpg) 

表结构:  

   和excel表的结构是一样的。
   每一列都是一类数据 --- 字段
   每一行代表一条数据 --- 记录

 

##  2.3 安装客户端

MySQL是一款C/S结构的软件。

MySQL本身是服务器端。

常见的客户端: CMD 、 Navicat、 Sqlyog、 phpmyadmin等等



安装 Navicat

1）解压

![img](assets/wps45C1.tmp.jpg) 

 

2) 选择安装版本

![img](assets/wps45C2.tmp.jpg) 

3)选择安装路径

![1528170859377](assets/1528170859377.png)

 

继续下一步...

 

4)链接服务器

![img](assets/wps45C4.tmp.jpg) 

 ① 点击“链接”按钮 ---  选择要链接的数据库种类

![img](assets/wps45C5.tmp.jpg) 

 

 ② 配置链接信息

   用户名： root       该用户是MySQL服务器系统的最高用户，拥有该系统的所有权限
   密码：  root             phpstudy中MySQL系统root用户的默认密码

![img](assets/wps45C6.tmp.jpg) 

 

  ③ 点击“localhost”结果

![img](assets/wps45C7.tmp.jpg) 

 

左侧的localhost下的内容都是数据库名称。

  information_schema、mysql、performance_schema 这三个是系统数据库。
  其他的都是自建数据库

看到上图，说明已经使用navicat 客户端正常链接到了 MySQL服务器了。



# 3. 创建/删除数据库

操作数据库需要使用SQL语句（结构化查询语言）

1) 创建数据库

​    语法格式: create database 库名;

​    示例: create database study;   创建一个名为 study的数据库

​              create database cms:     创建一个名为 cms 的数据库



![1534045491228](assets/1534045491228.png)

![1534045569648](assets/1534045569648.png)



![1534045609713](assets/1534045609713.png)







2) 删除数据库:

  语法格式:  drop database 库名;

  示例:     drop database school;  删除school库

​                drop database cms;      删除cms库



![1534045702681](assets/1534045702681.png)



# 4. 创建数据表

## 4.1 创建表的基本格式

语句格式:

CREATE TABLE 表名 (
       列名     数据类型(长度)    完整性约束条件,
       列名     数据类型(长度)    完整性约束条件,
       ......
) engine=myisam default charset=utf8

 

==注意事项:==
   ==列名、数据类型、长度是必有的； 完整性约束条件可以没有==
   ==最后的 utf8 没有 -==



## 4.2 创建用户表 -- users

案例:  在cms数据库中，创建一张users数据表，该表中只保存用户id和用户名两个字段

==一定要先选中 cms 库，再去打开查询编辑器== 

![1534046076681](assets/1534046076681.png)



![1534046277367](assets/1534046277367.png)



uid   int (5) :  uid字段是整型的，长度是5 (0--99999)

uname varchar(20): uname字段是字符串类型，长度是20 







# 5. 数据类型和完整性约束条件

## 5.1 数据类型

1) 整型:   int

​    tinyint（微整型 -128~~127）  
    int(-2,147,483,648  ~~ 2,147,483,647)

 2) 字符串:

​     varchar: 可变长度  varchar(30)    存储abc，varchar会占用3位长度
     char: 固定长度     char(30)    存储abc，char会占用30位长度
     char的执行速度比varchar快，所以能用char就用char

3) 枚举:  enum （单选）  

​    enum(‘男’, ‘女’, '人妖')   
    enum(‘武侠’, ‘玄幻’, ‘恐怖’, ‘都市言情’)



   set(多选)

   set('古装','喜剧','警匪','恐怖','穿越','动作')



4) 日期:  

​    date :   年-月-日
​    datetime :  年-月-日  时:分:秒
    (time： 时:分:秒)
    int: 存储时间戳



5) 文本: text  大文本



## 5.2 完整性约束条件

 完整性约束条件，就是进一步限制字段中保存的数据

1) unsigned: 无符号，只用在整型字段上。

   tinyint unsigned  无符号微整型 0~~255 

   int unsigned  0~~42亿

2) auto_increment: 自增长，只用在整型字段上。 

3) primary key: 主键。 

​      主键: 用来标志唯一一行数据的。

​      特点:  唯一 、 非空 、经常和auto_increment结合使用。 主键和自增长配合就能确定唯一的一条数据了。 主键一般都会选择整型字段。

4) unique: 唯一。 该列中不能出现重复值

5) not null: 非空。 该列中不能有 NULL 数据。	



## 5.3 创建管理员基本信息表 （ali_admin）

  所需字段:
    id:  整型 无符号  自增长  主键
    邮箱(账号、用户名):  字符串  唯一  非空
    昵称:  字符串  唯一 非空
    密码:  字符串  非空  md5加密(32位固定长度)
    手机:  字符串
    性别:  枚举，男、女、人妖
    生日:  日期  (date  datetime  int)
    年龄:  微整型，无符号
    个人介绍: 文本
    添加时间:  整型，记录时间戳



![1534048099271](assets/1534048099271.png)

```
create table ali_admin(
  admin_id int UNSIGNED auto_increment primary key,
  admin_email varchar(30) UNIQUE not null,
  admin_nickname varchar(30) UNIQUE not null,
  admin_pwd char(32) not null,
  admin_tel char(11),
  admin_gender enum('男','女','人妖'),
  admin_brith date,
  admin_age tinyint unsigned,
  admin_sign text,
  admin_addtime int UNSIGNED
)engine=myisam DEFAULT charset=utf8;
```

# **PHP核心编程-day5**

每日目标

- 能够使用SQL语句查询数据
- 能够使用SQL语句添加数据
- 能够使用SQL语句删除数据
- 能够使用SQL语句修改数据



# 1. 关系型数据库

##   1.1 关系型数据库简介

案例: 创建一个数据表，能够保存学生的基本信息(学号、姓名、年龄等)和学生每一科的考试成绩

1)  一张表的形式

![img](assets/03.jpg) 

缺点: 重复数据太多（数据冗余）

 

2) 关系型数据库:

![1528187325051](assets/02.png)

 

缺点: 表多
优点:
   数据耦合性低
   每个数据表都能够独立管理





##   1.2 student 和 dept表

   目标: 创建student和dept表用来存储学生的基本信息、学院基本信息和学生所属的学院信息

![1534172874473](assets/04.png)



   student：学生表，所需字段  学号、姓名、性别、年龄、系别

```
create table student(
  sno int UNSIGNED auto_increment primary key,
  sname varchar(20) not null,
  sage tinyint UNSIGNED not null,
  sgender enum('男','女') not null,
  sdept tinyint UNSIGNED not null
)engine=myisam default charset=utf8;
```



   dept：系别表，所需字段  系号  系名

```
create table dept(
  dept_id tinyint UNSIGNED auto_increment primary key,
  dept_name varchar(20) unique not null
)engine=myisam default charset=utf8;
```



##   1.3 ali_admin、ali_cate和ali_article的关系

   目标: 创建 ali_cate表和ali_article表，用来保存栏目基本信息、文章信息 以及 作者、栏目、文章的关系

![05](assets/05.png)



ali_cate表（栏目表）： 栏目id (主键)、 栏目名、栏目别名、栏目创建时间

```
create table ali_cate(
  cate_id tinyint UNSIGNED auto_increment primary key,
  cate_name varchar(10) unique not null,
  cate_slug varchar(30) UNIQUE not null,
  cate_addtime date not null
)engine=myisam default charset=utf8;
```



ali_article（文章表）： 文章id（主键）、文章标题、文章内容、文章作者、所属栏目、发布时间、文章状态（草稿、已发布）

```
create table ali_article(
  article_id int UNSIGNED auto_increment primary key,
  article_title varchar(30) UNIQUE not null,
  article_content text not null,
  article_adminid int UNSIGNED not null,
	article_cateid tinyint UNSIGNED not null,
  article_addtime int not null,
  article_state enum('草稿','已发布')
)engine=myisam default charset=utf8;
```





# 2. **数据查询**

语法格式: 

SELECT  字段名1, 字段名2, ......

  FROM 表名	

​      [ WHERE <条件表达式> ]

​      [ ORDER BY <字段名> [ ASC|DESC ]]

​      [ LIMIT  START, LENGTH]

 

##  2.1 基本查询

格式:  select  字段名1, 字段名2,....  from  表名 

 案例1: 查询所有栏目的id和名称

 表:  ali_cate

 字段:  cate_id、cate_name

![1534213675206](assets/1534213675206.png)



 案例2: 查询管理员信息 (全部字段信息)

表: ali_admin

字段: 所有字段



方式一:  在select和from之间，列出所有字段

![1534213763761](assets/1534213763761.png)



方式二: 使用 * 来代表所有字段

![1534213822095](assets/1534213822095.png)





##  2.2 带where子句的查询

select  field1, field2... from 表名  查询表中的所有数据

  where 可以使用条件来筛选查询出的结果

![img](assets/01.jpg) 

 

案例3: 查询id值为2的栏目的所有信息

表: ali_cate

字段:  *

筛选条件:  cate_id = 2

![1534214952123](assets/1534214952123.png)



案例4: 查询年龄大于等于25的管理员的邮箱和昵称

表: ali_admin

字段:  admin_email、 admin_nickname

筛选条件:  admin_age >= 25

![1534215147258](assets/1534215147258.png)



案例5: 查询年龄在23-28之间的管理员的所有信息

表: ali_admin

字段: *

筛选条件： admin_age>=23  and  admin_age<=28



方法一:

![1534215257922](assets/1534215257922.png)



方式二:

![1534215324315](assets/1534215324315.png)



案例6: 查询年龄不在23-28之间的管理员的所有信息

表: ali_admin

字段: *

筛选条件： `admin_age<23  or  admin_age>28`

方法一:

![1534215426973](assets/1534215426973.png)



方法二：

![1534215454171](assets/1534215454171.png)



案例7: 查询年龄大于25的男性管理员信息

表: ali_admin

字段:  *

筛选条件:  admin_age>=25 and admin_gender='男'

![1534215590016](assets/1534215590016.png)



##  2.3 in关键词

集合:  一组相同类型的数据，使用()来包含，括号内使用 ， 分隔开

(1, 2, 3, 4, 5)  (‘潮科技’, ‘会生活’, ‘奇趣事’, ‘美奇迹’)  

 

案例8: 查询年龄为20、28的女性管理员信息

表： ali_admin

字段： *

筛选条件： admin_gender='女'  and  （admin_age=20 or admin_age=28）



方式一:

![1534215841500](assets/1534215841500.png)



方式二：

![1534215898938](assets/1534215898938.png)



##  2.4 模糊查询

通配符:

  %: 代表任意长度(包括0)的任意字符

  _:  代表1位长度的任意字符

​    a%b :  ab  abb  a对萨达b
    a_b: acb  atb  a的b
    a_b%:  acb  a&baaad

like: 在执行模糊查询时，必须使用like来作为匹配条件



案例9: 查询邮箱地址中包含字符h的管理员信息

表： ali_admin

字段： *

筛选条件： admin_email like '%h%'

![1534216354094](assets/1534216354094.png)



案例10: 查询包含“科技”关键词的文章信息

表： ali_article

字段： *

筛选条件：admin_title like ‘%科技%’

![1534216526440](assets/1534216526440.png)





案例11: 查询邮箱以a字符开头并且包含n的管理员信息

表： ali_admin

字段： *

筛选条件： admin_email like ‘a%n%’

![1534216625722](assets/1534216625722.png)





##  2.5 order by 排序

order by 可以对查询结果按某个字段的升降进行排序

  升序 asc （默认值） ，  降序 desc 

可进行排序的字段通常是  整型  英文字符串型  日期型  (中文字符串也行,但一般不用)



案例12: 查询所有的栏目信息，并按别名的降序排列

表： ali_cate

字段：*

排序条件： cate_slug  desc

![1534216794928](assets/1534216794928.png)



案例13: 查询所有栏目信息，并按发布时间升序排列

表：ali_cate

字段： *

排序条件：cate_addtime asc

![1534216877104](assets/1534216877104.png)



案例14: 查询所有男性的管理员信息，并按照创建时间降序排列

表： ali_admin

字段：*

筛选条件： admin_gender='男'

排序：admin_addtime desc

![1534217036912](assets/1534217036912.png)

 

##  2.6 limit 限制

limit用来限制查询结果的起始点和长度

 格式:  limit  var1, var2

 var1: 起始点。 查询结果的索引，从0开始。 0代表第一条数据

 var2: 长度

 

案例15: 查询年龄最大的3名男性管理员的信息

表： ali_admin

字段： *

筛选： admin_gender='男'

排序：order by admin_age desc

限制：limit 0,3



![1534218129029](assets/1534218129029.png)



案例16: 将文章按发布时间逆序排列，并取出第三条到第五条

表： ali_article

字段：*

排序： article_addtime desc

限制：limit 2,3

![1534218422235](assets/1534218422235.png)



将 *  解释成对应的字段需要 0.0001秒，但是人多了之后就会变慢。



##  2.7 多表查询

关键词: join   on

 

格式:  

select  *  from  表1

  join 表2  on  链接条件

链接条件一定是   表1的某个字段 =  表2的某个字段



案例: 查询学生的全部信息，系别需要使用系名来进行显示

表： student     dept

字段: student.*   dept.dept_name



![1534219437090](assets/1534219437090.png)





原理:

![1534219689703](assets/1534219689703.png)



案例17: 查询所有文章信息，作者使用昵称显示

表： ali_article   ali_admin

字段： ali_article.*   ali_admin.admin_nickname

![1534220115051](assets/1534220115051.png)



案例18: 查询大牛发布的所有文章信息，作者使用昵称显示

表： ali_article   ali_admin

筛选： admin_nickname='大牛'

![1534220239981](assets/1534220239981.png)



案例19: 查询属于潮科技和奇趣事的所有文章

表：ali_cate   ali_article

筛选条件： cate_name in ('潮科技', '奇趣事')

![1534220507814](assets/1534220507814.png)



案例20: 查询所有文章信息，作者使用昵称显示，栏目使用栏目名显示

表： ali_article    ali_admin   ali_cate

![1534220828795](assets/1534220828795.png)



 

# 3. 添加数据

# 4. 修改数据

格式:  

  update  表名   set   字段1=值1, 字段2=值2,...  where  修改条件

  修改表中的哪一条（几条）数据的 字段1=值1...

 

案例21: 将id为6的管理员昵称改为凯子





案例22: 将所有男性管理员的年龄都+1







# 5. **删除数据**

格式:  delete from 表名  where 删除条件

 

案例25: 删除cate_id=5的栏目

# **PHP核心编程-day6**

每日目标

- 能够完成学生信息列表页

- 能够添加新学生信息

- 能够删除学生信息

- 能够修改学生信息

# 添加数据

格式： insert  into  表名(字段1，字段2，...)  values(值1，值2，...);

关键点:

   1) 字段和值需要一一对应，如果不对应会造成添加失败或者数据错误
   2) 如果每个字段都有数据，则不需要在表名后设置字段列表
   3) 带有auto_increment属性的字段可以使用null来设置，MySQL会自动填充数据



案例1: 向student表添加一条数据



方式一:

![1534295770586](assets/1534295770586.png)



方式二:

![1534295979697](assets/1534295979697.png)



方式三: 

![1534296150393](assets/1534296150393.png)



# 修改数据

格式:  

  update  表名   set   字段1=值1, 字段2=值2,...  where  修改条件

  修改表中的哪一条（几条）数据的 字段1=值1...

 

案例2: 将id为6的管理员昵称改为凯子

![1534297306985](assets/1534297306985.png)



案例3: 将所有男性管理员的年龄都+1

表: ali_admin

字段: admin_age

修改条件: admin_gender='男'

![1534297543190](assets/1534297543190.png)



# 删除数据

格式:  delete from 表名  where 删除条件

 

案例4: 删除cate_id=5的栏目

![1534297771122](assets/1534297771122.png)





![1534297834108](assets/1534297834108.png)



# 1. PHP操作MySQL

   PHP当中一共有三组函数可以用来操作MySQL服务器： mysql    mysqli   pdo



   PHP操作数据库是固定流程，一共6步:

   1) 链接MySQL服务器  

   2) 选择要操作的数据库

   3) 设置字符集 （不设置字符集可能会出现乱码问题）

   4) 执行SQL语句

   5) 处理SQL执行结果

   6) 关闭MySQL链接

   除了第五步，其他每一步都是固定的，对应一个mysql的函数



   1) 链接MySQL服务器 --- mysql_connect(var1, var2, var3)

  参数1: MySQL数据库的主机地址
  参数2: MySQL用户名  （root）
  参数3: 用户名对应的密码
  返回值: 数据库链接资源

  `$conn = mysql_connect('localhost', 'root', 'root');`

 

   2) 选择要操作的数据库  --- mysql_select_db(var)

  参数1: 数据库名称

 `mysql_select_db('demo');`

 

   3) 设置字符集 --- mysql_query(var);

  参数1: sql 语句 ----  set names utf8  (设置字符集的sql语句)

  `mysql_query('set names utf8'); `



   4) 执行SQL语句 --- mysql_query(var);

  参数: sql 语句 ----  增删改查SQL语句
  返回值: 如果是查询，则返回结果集（资源），该资源里面包含了从数据表中取出的数据
                如果是增删改，则返回布尔值，执行成功返回true，失败返回false

  `$result = mysql_query($conn, $sql); `



   5) 处理**==查询结果==**

  **==mysql_fetch_assoc(var);==**

  参数: 查询结果集（资源）
  返回值: 一维数组，下标是数据表字段

  将当前行的数据取出并返回成一维数组，同时将指针向下移动一行。
  如果已经无法返回一维数组时，则返回false 



   6) 关闭MySQL链接资源 --- mysql_close(var)

   参数: 数据库链接资源



案例: 向test库中的student表中，增加一条数据

![1534299226350](assets/1534299226350.png)

![1534299257926](assets/1534299257926.png)



 案例: 查询student表，并将数据以表格形式显示在网页上

![1534302509227](assets/1534302509227.png)

![1534302540798](assets/1534302540798.png)

![1534302553169](assets/1534302553169.png)



核心: mysql_fetch_assoc的执行原理

![1534302580309](assets/1534302580309.png)






# 2. 学生信息管理系统

**==目标: 通过PHP网页来管理数据库，对数据表的数据进行增删改查==**

  数据表设计:

​    sno： 学号  整型  无符号  主键  自增长
    sname： 姓名  字符串
    sage： 年龄 无符号 微整型
    sgender： 性别 枚举
    semail： 邮箱
    stel： 电话



​    create table student(
	sno int UNSIGNED auto_increment PRIMARY key,
	sname VARCHAR(30) not null,
	sage tinyint UNSIGNED not null,
	sgender enum('男', '女') DEFAULT '男',
	semail varchar(30),
	stel   char(11)
    ) engine=myisam DEFAULT charset=utf8;



测试数据:

INSERT INTO `student` VALUES ('1', '赵老四', '30', '男', 'zls@a.com', '13512345678');
INSERT INTO `student` VALUES ('2', '王翠花', '28', '女', 'wch@b.com', '13612345678');
INSERT INTO `student` VALUES ('3', '孙狗剩', '32', '男', 'sgs@c.com', '13712345678');





## 2.1  学生信息列表

 核心SQL:  select  *  from  student

 将student表的数据以表格形式显示在网页上

![1534258428616](assets/01.png)



 1) 从student表中获取数据

![1534303266774](assets/1534303266774.png)



2) 将获取的数据显示表格

![1534303304520](assets/1534303304520.png)



3) 释放资源

![1534303325933](assets/1534303325933.png)



## 2.2  添加学生信息

 核心SQL:  insert into student values(null, '路飞', 10, '男', 'lf@dasd.com', 18012345678);

![1528439313954](assets/02.png)



代码实现:

add.html  ----   提供一个可以填写的表单

![1534305511046](assets/1534305511046.png)



 add_deal.php

  1) 接收表单数据

  2) 拼接SQL语句

  3) 链接MySQL服务器并执行SQL语句

  4) 处理SQL执行结果： 判断结果，如果是true说明添加成功，如果是false说明添加失败

  5) 关闭数据库链接

![1534305668178](assets/1534305668178.png)

![1534305682999](assets/1534305682999.png)





##   2.3 删除学生

 核心SQL:  ==delete from student where sno=**5**==

 

![1525930130559](assets/03.png)

步骤: 
   1) 在学生信息列表页(index.php)，为每一行都添加一个删除按钮，删除按钮可以跳转到另一个php(del.php)页面，在跳转时，将当前行的sno一起传递到del.php页面。



![1534306751175](assets/1534306751175.png)



   2) del.php页面，接收sno，拼接删除的sql语句，再执行该SQL。再根据删除结果提示删除成功/删除失败。跳转回学生列表页。

  ① 接收学号 sno

  ② 拼接删除的SQL语句

  ③ 链接MySQL服务器并执行SQL语句

![1534306776699](assets/1534306776699.png)

![1534306790027](assets/1534306790027.png)





# 3. mysql其他函数

```
array mysql_fetch_row($resource)     功能同mysql_fetch_assoc，但取出的索引数组
array mysql_fetch_array($resource)   功能同mysql_fetch_assoc，但取出关联和索引的混合数组

int  mysql_num_rows($resource)  获取查询结果集中的行数
int  mysql_num_fields($resource)  获取查询结果集中的字段数
```

# PHP核心编程-day7

每日目标

- 说出什么是cookie以及cookie的原理

- 说出什么是session以及session的原理

- 能够完成学生管理系统的登录操作

  

# 1. 修改学生信息

核心：构造一条修改数据的SQL语句   

   ==update student set sname='', sage=''..  where sno=6==

![1525931034561](assets/04.png)



步骤:

 1) 在学生列表页(list.php)为每一行都添加一个“编辑”按钮，跳转到编辑表单页(edit.php)，并且要将当前行的sno一起传递到edit.php页面。

![1534470480931](assets/1534470480931.png)



 2) 创建edit.php页面(和add.html页面结构一样)，接收sno，拼接SQL语句并执行，得到一个一维数组，将该数组的值填充到表单中。

  ① 接收sno

  ② 根据sno 查询学生信息

  ③ 将学生信息显示到表单中  -- 将add.html中的表单复制过来，稍作修改即可

  ④ 保证表单能够提交到modify.php页面即可

![1534472770097](assets/1534472770097.png)

![1534472786290](assets/1534472786290.png)







 3) 创建一个修改页面(modify.php)，接收edit.php页面表单中的值，拼接一个修改的SQL语句，执行该SQL语句。根据修改结果提示修改成功/修改失败，再跳转

 ① 接收表单提交的数据

 ② 编写修改的SQL语句 --- update

 ③ 链接MySQL服务器并执行SQL语句

![1534472861491](assets/1534472861491.png)

![1534472871239](assets/1534472871239.png)





关于排错: 

​     核心思想: 如果一个程序中有SQL语句执行，那么该程序出现错误，第一反应去检查SQL语句。

​     检查方法:

​          1) 在php页面中使用echo 将sql语句进行输出

​           2) 在页面上复制SQL语句到navicat中进行测试



   第一步:![1534471889871](assets/1534471889871.png)

  第二步:

![1534471933626](assets/1534471933626.png)

  第三步:

![1534472010096](assets/1534472010096.png)

  将SQL语句复制到navicat中执行，获取错误信息。

![1534472183035](assets/1534472183035.png)





# 2. 登录

![1534422493447](assets/01.png) 



验证逻辑:

 1) 根据用户名从ali_admin表中查询数据。如果有结果，则说明用户名正确；反之，说明用户名错误。

 2) 登录表单提交密码和上一步查询出的密码进行比对，两者相等说明密码正确；反之，密码错误。



 代码实现:

1) 创建login.html 登录表单页

![1534475186781](assets/1534475186781.png)



2)  创建check.php文件

  ① 接收表单提交的数据

  ② 验证用户名是否正确

​      核心思路:  根据接收的用户名查询ali_admin表，如果能够查询到数据，说明用户名正确；反之，查询不到数据说明用户名错误。

​       核心SQL: ==select * from ali_admin where admin_email='$email'==

​       该SQL语句的执行结果，只能是0条数据 或者 1条数据

  ③ 验证密码是否正确

   核心思路:  验证从数据表中查询出的数据中的密码和表单提交的密码是否一致。如果一致，则说明密码正确，可以正常登录；反之，说明密码错误，跳转到login.html页面



![1534475375825](assets/1534475375825.png)

![1534475387591](assets/1534475387591.png)







测试: 直接访问 list.php页面，依然可以看到页面结果。 因为http协议是无记忆协议，不知道哪个浏览器来过，所以没办法限制是否能够正常访问到哪个页面。

要实现限制的功能，必须配合 ==会话控制== 技术



#3. **会话控制概述**

1) http协议的缺陷

​     无状态，就是无记忆，不能让同一浏览器和服务器进行多次数据交换时，产生业务的连续性。

2) 什么是会话控制

​     会话控制就是解决http无记忆的缺陷的。能够==将数据持久化的保存在客户端(浏览器)或者服务器端==，从而让浏览器和服务器进行多次数据交换时，产生连续性。

3) 会话控制的分类

​    分为两种: cookie（客户端）  和  session（服务器端）



cookie应用实例 --- 千人千面（猜你喜欢）

![1534424615529](assets/02.png)



不同的用户访问优酷服务器所看的视频类型不一样。 服务器会将浏览器观看过的视频的关键词保存到浏览器的cookie中（文件、内存）。当浏览器再次访问优酷服务器时，服务器会从cookie中读取关键词，再根据关键词推荐视频。





session应用实例 --- 支付宝

![1534426142105](assets/1534426142105.png)



每个用户访问支付宝进行登录时，用的是同一套程序。服务器会为每一个浏览器进行编号(sessionid)，当用户登录成功后，服务器会创建一个区域(文件、内存服务器)用来保存用户信息。等浏览器下一次访问服务器时，服务器先拿到浏览器的编号，再和已有的编号进行比较，找到相同的区域（文件、内存服务器）。





# 4. cookie技术

##  4.1 什么是cookie？

   cookie是将数据持久化存储到客户端的一种技术。

   网站可以将数据写到浏览器中， 一个网站最多能在一个浏览器写20个cookie。

   一个浏览器能够设置的总cookie数最多为300个，每个不能超过4kb。

   cookie既能保存在文件中，也能保存在内存中。



##  4.2 设置/读取cookie

 1) 设置cookie

   setcookie(var1 , var2, var3);
   var1: cookie的名称
   var2: 名称对应的值， 可选参数
   var3: cookie的有效期， 可选参数

 ![1534478105079](assets/1534478105079.png)



2) 读取cookie信息

   使用php的超全局变量 $_COOKIE进行读取

![1534478123739](assets/1534478123739.png)





通过浏览器查看cookie信息:

![1534478176053](assets/1534478176053.png)

![1534478276084](assets/1534478276084.png)





## 4.3 cookie有效期

  setcookie函数的参数3可以控制cookie有效期
	参数3设置为-1 或者 不设置，关闭浏览器即失效
	参数3设置为 time()+秒数，则在当前时间点的多少秒之后失效



  设置cookie时，如果设置了有效期，则cookie会保存在文件中；如果没有设置有效期，则cookie保存在内存中。



## 4.4 cookie的有效范围

​    ==setcookie函数还有参数4、5，可以用来控制cookie的有效访问，但是**一般不用**。==

只需要记住下面的情况即可：    
    在不使用参数4和5的情况下，cookie在当前目录及子目录中有效，在上层目录中无效。



![1534478631803](assets/1534478631803.png)





## 4.5 cookie删除

​    setcookie函数第二个参数设置为null，就可以删除cookie
    setcookie('name', null);

![1534478730006](assets/1534478730006.png)



## 4.6 js控制cookie

cookie是将数据保存在客户端的，所以可以使用javascript来读取/设置cookie。 

​   设置cookie:   document.cookie = “名称=值;expires=时间”
​   读取cookie:   document.cookie



读取cookie:

![1534479056017](assets/1534479056017.png)

![1534479028505](assets/1534479028505.png)





设置cookie:

  expires: 用来指定cookie有效期的

![1534479410042](assets/1534479410042.png)



# 5. session技术

## 5.1 session介绍

因为cookie是保存在客户端的数据，不够安全，所以出现了session。
session会将数据保存到服务器端（保存在==文件==、内存服务器或数据表中），安全性就可以得到保证。



## 5.2 设置/读取session

   重点:
	php使用session时，首先要使用session_start()函数来开启session。
	$_SESSION 超全局变量就能设置和读取session中的内容

1) 设置session

   将session作为数组操作就可以。

![1534479772737](assets/1534479772737.png)



2) 读取session

![1534479789250](assets/1534479789250.png)





## 5.3 session作用范围

   在当前网站的任何一个页面设置过session，则该网站的所有页面都能得到该session的数据
   例如: 在 www.jd.com 的某个页面中设置session，那么在jd网站的任何一个页面都能找到该session
             同理，在localhost的某个页面中设置session，那么在localhost的任何一个php页面都能找到



![1534480032772](assets/1534480032772.png)





## 5.4 session的有效期

   浏览器关闭时，session消失



## 5.5 删除session

   unset($_SESSION[‘name’]);    //删除单个session
   session_destroy();                   //删除所有session



![1534480227294](assets/1534480227294.png)

 



# 6. 登录功能完善

   核心思想: 
 	1) 登录成功时将用户重要信息写入session  ---  将登录用户的主要信息记入session
	2) 在其他每个页面中都进行session是否存在的验证



1) 登录成功时，设置session



2) 在其他页面中检测session是否存在



3) 将检测session 的代码复制到每个页面中，除了 login.html 和 check.php



# 7. 会话控制小结

## 7.1 cookie原理

## 7.2 session和cookie的联系

1) cookie的原理

​    使用浏览器访问设置cookie的页面时，cookie信息会随着响应头返回给浏览器，并保存在浏览器中





2) session原理

​    session默认是保存在服务器的文件当中的。
    windows默认存放在 c:/windows/temp目录下，==phpstudy存放在 phpstudy/tmp/tmp目录下==





3) cookie和session的联系

​     当浏览器访问一个设置session的页面时，服务器会随机自动生成一个session_id（字符串）。返回给浏览器，并保存在浏览器的cookie当中，同时服务器中也会生成一个以该session_id为名称的文件，用来记录信息。

​     之后每次访问该网站时，都会携带cookie中的session_id，来和服务器中的session文件名进行比对。当文件名和cookie中的session_id一致时，则说明使用的是该session文件，可以从该session文件中读取数据。



案例: 访问 setsession.php文件 和  getsession.php



访问 setsession.php文件时，完成两件事情

1) 将session_id随着响应头返回给浏览器，并保存在浏览器中





2) 在服务器端创建一个session文件   sess_sud7ihet8nkm6shinsjekaufv7， 将$_SESSION中已保存的数据，存储到该文件中。





getsession.php文件





## 7.3 session和cookie总结

 cookie小结:

  1） 将数据保存在客户端，安全性不好，但是可以保存的数据量较大。
  2） 设置cookie使用  setcookie(var1, var2, var3)；
	var1： cookie名称
	var2： 名称对应的值
	var3： 有效期。 可选参数，如果不设置该值或者设置为-1，浏览器关闭则cookie消失
  3） 使用$_COOKIE 预定义数组来读取cookie
  4） cookie的有效范围： 当前目录及子目录；上级目录无效
  5） 删除cookie:  setcookie(‘name’, null);

 

 session小结:

  1) 将数据保存在服务器端，安全性高，但是不能保存大量的数据。一般来讲session当中保存的都是用户信息。
  2) 使用session时，首先要使用 session_start函数开启session
  3) 设置和读取session时，都是用`  $_SESSION['name'] = 'zs';  $_SESSION['name'];`
  4) session的有效范围，在一个域名下设置session，在整个域名范围内都有效
  5) 删除session
	unset($_SESSION[‘name’]);    //删除单个session
	session_destroy();                   //删除所有session


基于jQuery的$.ajax()方法实现登录验证功能，已知后台URL地址如下：http://localhost/user/check 
请求参数要求：username和password 
请求方式要求：POST




























